package com.github.processx.dal.dataobjects;

import java.util.Date;

public class ProcessInstanceDO {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_instance.id
   *
   * @mbggenerated
   */
  private Long id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_instance.process_id
   *
   * @mbggenerated
   */
  private Long processId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_instance.biz_no
   *
   * @mbggenerated
   */
  private String bizNo;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_instance.create_time
   *
   * @mbggenerated
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_instance.modified_time
   *
   * @mbggenerated
   */
  private Date modifiedTime;

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_instance
   *
   * @mbggenerated
   */
  public ProcessInstanceDO(Long id, Long processId, String bizNo, Date createTime, Date modifiedTime) {
    this.id = id;
    this.processId = processId;
    this.bizNo = bizNo;
    this.createTime = createTime;
    this.modifiedTime = modifiedTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_instance
   *
   * @mbggenerated
   */
  public ProcessInstanceDO() {
    super();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_instance.id
   *
   * @return the value of process_instance.id
   * @mbggenerated
   */
  public Long getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_instance.id
   *
   * @param id the value for process_instance.id
   * @mbggenerated
   */
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_instance.process_id
   *
   * @return the value of process_instance.process_id
   * @mbggenerated
   */
  public Long getProcessId() {
    return processId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_instance.process_id
   *
   * @param processId the value for process_instance.process_id
   * @mbggenerated
   */
  public void setProcessId(Long processId) {
    this.processId = processId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_instance.biz_no
   *
   * @return the value of process_instance.biz_no
   * @mbggenerated
   */
  public String getBizNo() {
    return bizNo;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_instance.biz_no
   *
   * @param bizNo the value for process_instance.biz_no
   * @mbggenerated
   */
  public void setBizNo(String bizNo) {
    this.bizNo = bizNo == null ? null : bizNo.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_instance.create_time
   *
   * @return the value of process_instance.create_time
   * @mbggenerated
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_instance.create_time
   *
   * @param createTime the value for process_instance.create_time
   * @mbggenerated
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_instance.modified_time
   *
   * @return the value of process_instance.modified_time
   * @mbggenerated
   */
  public Date getModifiedTime() {
    return modifiedTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_instance.modified_time
   *
   * @param modifiedTime the value for process_instance.modified_time
   * @mbggenerated
   */
  public void setModifiedTime(Date modifiedTime) {
    this.modifiedTime = modifiedTime;
  }
}