package com.github.processx.dal.dataobjects;

import java.util.Date;

public class ProcessNodeInstanceDO {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_node_instance.id
   *
   * @mbggenerated
   */
  private Long id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_node_instance.process_instance_id
   *
   * @mbggenerated
   */
  private Long processInstanceId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_node_instance.biz_no
   *
   * @mbggenerated
   */
  private String bizNo;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_node_instance.node_id
   *
   * @mbggenerated
   */
  private Long nodeId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_node_instance.status
   *
   * @mbggenerated
   */
  private Integer status;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_node_instance.failed_count
   *
   * @mbggenerated
   */
  private Integer failedCount;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_node_instance.exec_count
   *
   * @mbggenerated
   */
  private Integer execCount;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_node_instance.recover_time
   *
   * @mbggenerated
   */
  private Date recoverTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_node_instance.create_time
   *
   * @mbggenerated
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_node_instance.modified_time
   *
   * @mbggenerated
   */
  private Date modifiedTime;

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_node_instance
   *
   * @mbggenerated
   */
  public ProcessNodeInstanceDO(Long id, Long processInstanceId, String bizNo, Long nodeId, Integer status, Integer failedCount, Integer execCount, Date recoverTime, Date createTime, Date modifiedTime) {
    this.id = id;
    this.processInstanceId = processInstanceId;
    this.bizNo = bizNo;
    this.nodeId = nodeId;
    this.status = status;
    this.failedCount = failedCount;
    this.execCount = execCount;
    this.recoverTime = recoverTime;
    this.createTime = createTime;
    this.modifiedTime = modifiedTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_node_instance
   *
   * @mbggenerated
   */
  public ProcessNodeInstanceDO() {
    super();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_node_instance.id
   *
   * @return the value of process_node_instance.id
   * @mbggenerated
   */
  public Long getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_node_instance.id
   *
   * @param id the value for process_node_instance.id
   * @mbggenerated
   */
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_node_instance.process_instance_id
   *
   * @return the value of process_node_instance.process_instance_id
   * @mbggenerated
   */
  public Long getProcessInstanceId() {
    return processInstanceId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_node_instance.process_instance_id
   *
   * @param processInstanceId the value for process_node_instance.process_instance_id
   * @mbggenerated
   */
  public void setProcessInstanceId(Long processInstanceId) {
    this.processInstanceId = processInstanceId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_node_instance.biz_no
   *
   * @return the value of process_node_instance.biz_no
   * @mbggenerated
   */
  public String getBizNo() {
    return bizNo;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_node_instance.biz_no
   *
   * @param bizNo the value for process_node_instance.biz_no
   * @mbggenerated
   */
  public void setBizNo(String bizNo) {
    this.bizNo = bizNo == null ? null : bizNo.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_node_instance.node_id
   *
   * @return the value of process_node_instance.node_id
   * @mbggenerated
   */
  public Long getNodeId() {
    return nodeId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_node_instance.node_id
   *
   * @param nodeId the value for process_node_instance.node_id
   * @mbggenerated
   */
  public void setNodeId(Long nodeId) {
    this.nodeId = nodeId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_node_instance.status
   *
   * @return the value of process_node_instance.status
   * @mbggenerated
   */
  public Integer getStatus() {
    return status;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_node_instance.status
   *
   * @param status the value for process_node_instance.status
   * @mbggenerated
   */
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_node_instance.failed_count
   *
   * @return the value of process_node_instance.failed_count
   * @mbggenerated
   */
  public Integer getFailedCount() {
    return failedCount;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_node_instance.failed_count
   *
   * @param failedCount the value for process_node_instance.failed_count
   * @mbggenerated
   */
  public void setFailedCount(Integer failedCount) {
    this.failedCount = failedCount;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_node_instance.exec_count
   *
   * @return the value of process_node_instance.exec_count
   * @mbggenerated
   */
  public Integer getExecCount() {
    return execCount;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_node_instance.exec_count
   *
   * @param execCount the value for process_node_instance.exec_count
   * @mbggenerated
   */
  public void setExecCount(Integer execCount) {
    this.execCount = execCount;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_node_instance.recover_time
   *
   * @return the value of process_node_instance.recover_time
   * @mbggenerated
   */
  public Date getRecoverTime() {
    return recoverTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_node_instance.recover_time
   *
   * @param recoverTime the value for process_node_instance.recover_time
   * @mbggenerated
   */
  public void setRecoverTime(Date recoverTime) {
    this.recoverTime = recoverTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_node_instance.create_time
   *
   * @return the value of process_node_instance.create_time
   * @mbggenerated
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_node_instance.create_time
   *
   * @param createTime the value for process_node_instance.create_time
   * @mbggenerated
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_node_instance.modified_time
   *
   * @return the value of process_node_instance.modified_time
   * @mbggenerated
   */
  public Date getModifiedTime() {
    return modifiedTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_node_instance.modified_time
   *
   * @param modifiedTime the value for process_node_instance.modified_time
   * @mbggenerated
   */
  public void setModifiedTime(Date modifiedTime) {
    this.modifiedTime = modifiedTime;
  }
}