package com.github.processx.dal.dataobjects;

import java.util.Date;

public class ProcessTriggerResultDO {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_trigger_result.id
   *
   * @mbggenerated
   */
  private Long id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_trigger_result.process_instance_id
   *
   * @mbggenerated
   */
  private Long processInstanceId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_trigger_result.biz_no
   *
   * @mbggenerated
   */
  private String bizNo;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_trigger_result.node_id
   *
   * @mbggenerated
   */
  private Long nodeId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_trigger_result.value
   *
   * @mbggenerated
   */
  private String value;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_trigger_result.create_time
   *
   * @mbggenerated
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column process_trigger_result.modified_time
   *
   * @mbggenerated
   */
  private Date modifiedTime;

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_trigger_result
   *
   * @mbggenerated
   */
  public ProcessTriggerResultDO(Long id, Long processInstanceId, String bizNo, Long nodeId, String value, Date createTime, Date modifiedTime) {
    this.id = id;
    this.processInstanceId = processInstanceId;
    this.bizNo = bizNo;
    this.nodeId = nodeId;
    this.value = value;
    this.createTime = createTime;
    this.modifiedTime = modifiedTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_trigger_result
   *
   * @mbggenerated
   */
  public ProcessTriggerResultDO() {
    super();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_trigger_result.id
   *
   * @return the value of process_trigger_result.id
   * @mbggenerated
   */
  public Long getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_trigger_result.id
   *
   * @param id the value for process_trigger_result.id
   * @mbggenerated
   */
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_trigger_result.process_instance_id
   *
   * @return the value of process_trigger_result.process_instance_id
   * @mbggenerated
   */
  public Long getProcessInstanceId() {
    return processInstanceId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_trigger_result.process_instance_id
   *
   * @param processInstanceId the value for process_trigger_result.process_instance_id
   * @mbggenerated
   */
  public void setProcessInstanceId(Long processInstanceId) {
    this.processInstanceId = processInstanceId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_trigger_result.biz_no
   *
   * @return the value of process_trigger_result.biz_no
   * @mbggenerated
   */
  public String getBizNo() {
    return bizNo;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_trigger_result.biz_no
   *
   * @param bizNo the value for process_trigger_result.biz_no
   * @mbggenerated
   */
  public void setBizNo(String bizNo) {
    this.bizNo = bizNo == null ? null : bizNo.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_trigger_result.node_id
   *
   * @return the value of process_trigger_result.node_id
   * @mbggenerated
   */
  public Long getNodeId() {
    return nodeId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_trigger_result.node_id
   *
   * @param nodeId the value for process_trigger_result.node_id
   * @mbggenerated
   */
  public void setNodeId(Long nodeId) {
    this.nodeId = nodeId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_trigger_result.value
   *
   * @return the value of process_trigger_result.value
   * @mbggenerated
   */
  public String getValue() {
    return value;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_trigger_result.value
   *
   * @param value the value for process_trigger_result.value
   * @mbggenerated
   */
  public void setValue(String value) {
    this.value = value == null ? null : value.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_trigger_result.create_time
   *
   * @return the value of process_trigger_result.create_time
   * @mbggenerated
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_trigger_result.create_time
   *
   * @param createTime the value for process_trigger_result.create_time
   * @mbggenerated
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column process_trigger_result.modified_time
   *
   * @return the value of process_trigger_result.modified_time
   * @mbggenerated
   */
  public Date getModifiedTime() {
    return modifiedTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column process_trigger_result.modified_time
   *
   * @param modifiedTime the value for process_trigger_result.modified_time
   * @mbggenerated
   */
  public void setModifiedTime(Date modifiedTime) {
    this.modifiedTime = modifiedTime;
  }
}