package com.github.processx.dal.daointerface;

import com.github.processx.dal.dataobjects.ProcessTriggerResultDO;
import java.util.List;

public interface ProcessTriggerResultDOMapper extends ProcessTriggerResultDOMapperBase {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_trigger_result
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_trigger_result
   *
   * @mbggenerated
   */
  int insert(ProcessTriggerResultDO record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_trigger_result
   *
   * @mbggenerated
   */
  ProcessTriggerResultDO selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_trigger_result
   *
   * @mbggenerated
   */
  List<ProcessTriggerResultDO> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_trigger_result
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(ProcessTriggerResultDO record);
}