package com.github.processx.dal.daointerface;

import com.github.processx.dal.dataobjects.ProcessSchedulePlanDO;
import java.util.List;

public interface ProcessSchedulePlanDOMapper extends ProcessSchedulePlanDOMapperBase {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_schedule_plan
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_schedule_plan
   *
   * @mbggenerated
   */
  int insert(ProcessSchedulePlanDO record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_schedule_plan
   *
   * @mbggenerated
   */
  ProcessSchedulePlanDO selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_schedule_plan
   *
   * @mbggenerated
   */
  List<ProcessSchedulePlanDO> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_schedule_plan
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(ProcessSchedulePlanDO record);
}