package com.github.processx.dal.daointerface;

import com.github.processx.dal.dataobjects.ProcessNodeDO;
import java.util.List;

public interface ProcessNodeDOMapper extends ProcessNodeDOMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_node
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_node
     *
     * @mbggenerated
     */
    int insert(ProcessNodeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_node
     *
     * @mbggenerated
     */
    ProcessNodeDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_node
     *
     * @mbggenerated
     */
    List<ProcessNodeDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_node
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProcessNodeDO record);
}