package com.github.processx.dal.daointerface;

import com.github.processx.dal.dataobjects.ProcessNodeInstanceDO;
import java.util.List;

public interface ProcessNodeInstanceDOMapper extends ProcessNodeInstanceDOMapperBase {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_node_instance
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_node_instance
   *
   * @mbggenerated
   */
  int insert(ProcessNodeInstanceDO record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_node_instance
   *
   * @mbggenerated
   */
  ProcessNodeInstanceDO selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_node_instance
   *
   * @mbggenerated
   */
  List<ProcessNodeInstanceDO> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_node_instance
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(ProcessNodeInstanceDO record);
}