package com.github.processx.dal.daointerface;

import com.github.processx.dal.dataobjects.ProcessNodeInputDO;
import java.util.List;

public interface ProcessNodeInputDOMapper extends ProcessNodeInputDOMapperBase {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_node_input
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_node_input
   *
   * @mbggenerated
   */
  int insert(ProcessNodeInputDO record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_node_input
   *
   * @mbggenerated
   */
  ProcessNodeInputDO selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_node_input
   *
   * @mbggenerated
   */
  List<ProcessNodeInputDO> selectAll();

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table process_node_input
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(ProcessNodeInputDO record);
}